export const mockGiggz = [
  {
    id: '#343178',
    client: 'Robert Fox',
    serviceProvider: 'Esther Howard',
    datePosted: 'Feb 25, 2022',
    status: 'Active',
    clientInfo: {
      name: 'Prince Chijioke',
      email: 'emekepeter@gmail.com',
      phone: '+234 903 828 3447',
      location: 'Lagos',
      address: '2972 Westheimer Rd. Santa Ana, Illinois 85486',
    },
    serviceProviderInfo: {
      name: 'Wokrit Gomam',
      email: 'alma.lawson@example.com',
      phone: '+234 903 828 3447',
      location: 'Lagos',
      address: '2972 Westheimer Rd. Santa Ana, Illinois 85486',
    },
    jobPosted: {
      title: 'Cooks Needed',
      description:
        'Lorem ipsum dolor sit amet consectetur. Molestie sit enim feugiat turpis urna id. Ullamcorper aenean aliquet turpis nulla. Purus ipsum risus pellentesque purus quis elit ormat nunc. Pretium in non iaculis posuere nec sagittis cras. Est morbi laoreet eut lorem. Leo ultricies amet suscipit mi est aliquet nisl imperdiet quam. Pretium.',
      postedDate: '2 wks ago',
    },
    giggLink: 'www.giggz.com/giggz?100002|shalj',
  },
  {
    id: '#370668',
    client: 'Cody Fisher',
    serviceProvider: 'Ronald Richards',
    datePosted: 'Feb 25, 2022',
    status: 'Active',
    clientInfo: {
      name: 'Prince Chijioke',
      email: 'emekepeter@gmail.com',
      phone: '+234 903 828 3447',
      location: 'Lagos',
      address: '2972 Westheimer Rd. Santa Ana, Illinois 85486',
    },
    serviceProviderInfo: {
      name: 'Wokrit Gomam',
      email: 'alma.lawson@example.com',
      phone: '+234 903 828 3447',
      location: 'Lagos',
      address: '2972 Westheimer Rd. Santa Ana, Illinois 85486',
    },
    jobPosted: {
      title: 'Cooks Needed',
      description:
        'Lorem ipsum dolor sit amet consectetur. Molestie sit enim feugiat turpis urna id. Ullamcorper aenean aliquet turpis nulla. Purus ipsum risus pellentesque purus quis elit ormat nunc. Pretium in non iaculis posuere nec sagittis cras. Est morbi laoreet eut lorem. Leo ultricies amet suscipit mi est aliquet nisl imperdiet quam. Pretium.',
      postedDate: '2 wks ago',
    },
    giggLink: 'www.giggz.com/giggz?100002|shalj',
  },
  {
    id: '#543756',
    client: 'Jane Cooper',
    serviceProvider: 'Wade Warren',
    datePosted: 'Feb 25, 2022',
    status: 'Ongoing',
    clientInfo: {
      name: 'Prince Chijioke',
      email: 'emekepeter@gmail.com',
      phone: '+234 903 828 3447',
      location: 'Lagos',
      address: '2972 Westheimer Rd. Santa Ana, Illinois 85486',
    },
    serviceProviderInfo: {
      name: 'Wokrit Gomam',
      email: 'alma.lawson@example.com',
      phone: '+234 903 828 3447',
      location: 'Lagos',
      address: '2972 Westheimer Rd. Santa Ana, Illinois 85486',
    },
    jobPosted: {
      title: 'Cooks Needed',
      description:
        'Lorem ipsum dolor sit amet consectetur. Molestie sit enim feugiat turpis urna id. Ullamcorper aenean aliquet turpis nulla. Purus ipsum risus pellentesque purus quis elit ormat nunc. Pretium in non iaculis posuere nec sagittis cras. Est morbi laoreet eut lorem. Leo ultricies amet suscipit mi est aliquet nisl imperdiet quam. Pretium.',
      postedDate: '2 wks ago',
    },
    giggLink: 'www.giggz.com/giggz?100002|shalj',
  },
  {
    id: '#422739',
    client: 'Wade Warren',
    serviceProvider: 'Cody Fisher',
    datePosted: 'Feb 25, 2022',
    status: 'Ongoing',
    clientInfo: {
      name: 'Prince Chijioke',
      email: 'emekepeter@gmail.com',
      phone: '+234 903 828 3447',
      location: 'Lagos',
      address: '2972 Westheimer Rd. Santa Ana, Illinois 85486',
    },
    serviceProviderInfo: {
      name: 'Wokrit Gomam',
      email: 'alma.lawson@example.com',
      phone: '+234 903 828 3447',
      location: 'Lagos',
      address: '2972 Westheimer Rd. Santa Ana, Illinois 85486',
    },
    jobPosted: {
      title: 'Cooks Needed',
      description:
        'Lorem ipsum dolor sit amet consectetur. Molestie sit enim feugiat turpis urna id. Ullamcorper aenean aliquet turpis nulla. Purus ipsum risus pellentesque purus quis elit ormat nunc. Pretium in non iaculis posuere nec sagittis cras. Est morbi laoreet eut lorem. Leo ultricies amet suscipit mi est aliquet nisl imperdiet quam. Pretium.',
      postedDate: '2 wks ago',
    },
    giggLink: 'www.giggz.com/giggz?100002|shalj',
  },
  {
    id: '#339635',
    client: 'Cameron Williamson',
    serviceProvider: 'Eleanor Pena',
    datePosted: 'Feb 25, 2022',
    status: 'Completed',
    clientInfo: {
      name: 'Prince Chijioke',
      email: 'emekepeter@gmail.com',
      phone: '+234 903 828 3447',
      location: 'Lagos',
      address: '2972 Westheimer Rd. Santa Ana, Illinois 85486',
    },
    serviceProviderInfo: {
      name: 'Wokrit Gomam',
      email: 'alma.lawson@example.com',
      phone: '+234 903 828 3447',
      location: 'Lagos',
      address: '2972 Westheimer Rd. Santa Ana, Illinois 85486',
    },
    jobPosted: {
      title: 'Cooks Needed',
      description:
        'Lorem ipsum dolor sit amet consectetur. Molestie sit enim feugiat turpis urna id. Ullamcorper aenean aliquet turpis nulla. Purus ipsum risus pellentesque purus quis elit ormat nunc. Pretium in non iaculis posuere nec sagittis cras. Est morbi laoreet eut lorem. Leo ultricies amet suscipit mi est aliquet nisl imperdiet quam. Pretium.',
      postedDate: '2 wks ago',
    },
    giggLink: 'www.giggz.com/giggz?100002|shalj',
  },
  {
    id: '#843178',
    client: 'Eleanor Pena',
    serviceProvider: 'Dianne Russell',
    datePosted: 'Feb 25, 2022',
    status: 'Completed',
    clientInfo: {
      name: 'Prince Chijioke',
      email: 'emekepeter@gmail.com',
      phone: '+234 903 828 3447',
      location: 'Lagos',
      address: '2972 Westheimer Rd. Santa Ana, Illinois 85486',
    },
    serviceProviderInfo: {
      name: 'Wokrit Gomam',
      email: 'alma.lawson@example.com',
      phone: '+234 903 828 3447',
      location: 'Lagos',
      address: '2972 Westheimer Rd. Santa Ana, Illinois 85486',
    },
    jobPosted: {
      title: 'Cooks Needed',
      description:
        'Lorem ipsum dolor sit amet consectetur. Molestie sit enim feugiat turpis urna id. Ullamcorper aenean aliquet turpis nulla. Purus ipsum risus pellentesque purus quis elit ormat nunc. Pretium in non iaculis posuere nec sagittis cras. Est morbi laoreet eut lorem. Leo ultricies amet suscipit mi est aliquet nisl imperdiet quam. Pretium.',
      postedDate: '2 wks ago',
    },
    giggLink: 'www.giggz.com/giggz?100002|shalj',
  },
  {
    id: '#797174',
    client: 'Darrell Steward',
    serviceProvider: 'Cameron Williamson',
    datePosted: 'Feb 25, 2022',
    status: 'Closed',
    clientInfo: {
      name: 'Prince Chijioke',
      email: 'emekepeter@gmail.com',
      phone: '+234 903 828 3447',
      location: 'Lagos',
      address: '2972 Westheimer Rd. Santa Ana, Illinois 85486',
    },
    serviceProviderInfo: {
      name: 'Wokrit Gomam',
      email: 'alma.lawson@example.com',
      phone: '+234 903 828 3447',
      location: 'Lagos',
      address: '2972 Westheimer Rd. Santa Ana, Illinois 85486',
    },
    jobPosted: {
      title: 'Cooks Needed',
      description:
        'Lorem ipsum dolor sit amet consectetur. Molestie sit enim feugiat turpis urna id. Ullamcorper aenean aliquet turpis nulla. Purus ipsum risus pellentesque purus quis elit ormat nunc. Pretium in non iaculis posuere nec sagittis cras. Est morbi laoreet eut lorem. Leo ultricies amet suscipit mi est aliquet nisl imperdiet quam. Pretium.',
      postedDate: '2 wks ago',
    },
    giggLink: 'www.giggz.com/giggz?100002|shalj',
  },
  {
    id: '#322739',
    client: 'Jacob Jones',
    serviceProvider: 'Marvin McKinney',
    datePosted: 'Feb 25, 2022',
    status: 'Closed',
    clientInfo: {
      name: 'Prince Chijioke',
      email: 'emekepeter@gmail.com',
      phone: '+234 903 828 3447',
      location: 'Lagos',
      address: '2972 Westheimer Rd. Santa Ana, Illinois 85486',
    },
    serviceProviderInfo: {
      name: 'Wokrit Gomam',
      email: 'alma.lawson@example.com',
      phone: '+234 903 828 3447',
      location: 'Lagos',
      address: '2972 Westheimer Rd. Santa Ana, Illinois 85486',
    },
    jobPosted: {
      title: 'Cooks Needed',
      description:
        'Lorem ipsum dolor sit amet consectetur. Molestie sit enim feugiat turpis urna id. Ullamcorper aenean aliquet turpis nulla. Purus ipsum risus pellentesque purus quis elit ormat nunc. Pretium in non iaculis posuere nec sagittis cras. Est morbi laoreet eut lorem. Leo ultricies amet suscipit mi est aliquet nisl imperdiet quam. Pretium.',
      postedDate: '2 wks ago',
    },
    giggLink: 'www.giggz.com/giggz?100002|shalj',
  },
]

export const giggzStats = {
  allGiggz: 35950,
  activeGiggz: 10405,
  completedGiggz: 16123,
  ongoingGiggz: 9210,
  closedGiggz: 212,
}
