export const mockUsers = [
  {
    id: 1,
    name: 'James Hadish',
    occupation: 'Web Designer',
    email: 'sara.cruz@example.com',
    balance: 'N20,000.00',
    dateRegistered: 'Feb 25, 2022',
    status: 'Verified',
    avatar: '/avatar-placeholder.png',
    phone: '+234 903 828 3447',
    state: 'Abuja',
    address: '2972 Westheimer Rd. Santa Ana, Illinois 85486',
    totalDeposited: 'NGN 200,000.00',
    totalSpent: 'NGN 100,000.00',
    currentBalance: 'NGN 100,000.00',
    jobsPosted: 2,
    hiredGiggz: 2,
    hoursPaid: 214,
    reviews: [
      {
        id: 1,
        title: 'Responsive client',
        content:
          'A wonderful client to work with! He had a clear vision for the project and provided detailed specifications. Communication was excellent throughout the process, and he was always responsive and accommodating. It was a pleasure bringing his ideas to life. Highly recommended!',
        reviewer: 'Suleman Blakes',
        rating: 4,
        date: '2 wks ago',
      },
      {
        id: 2,
        title: 'Responsive client',
        content:
          'A wonderful client to work with! He had a clear vision for the project and provided detailed specifications. Communication was excellent throughout the process, and he was always responsive and accommodating. It was a pleasure bringing his ideas to life. Highly recommended!',
        reviewer: 'Jenny Wilson',
        rating: 4,
        date: '2 wks ago',
      },
      {
        id: 3,
        title: 'Responsive client',
        content:
          'A wonderful client to work with! He had a clear vision for the project and provided detailed specifications. Communication was excellent throughout the process, and he was always responsive and accommodating. It was a pleasure bringing his ideas to life. Highly recommended!',
        reviewer: 'Courtney Henry',
        rating: 4,
        date: '2 wks ago',
      },
    ],
    jobs: [
      {
        id: 1,
        title: 'Cooks Needed',
        description:
          'Lorem ipsum dolor sit amet, consectetur. Molestie at arma feugiat turpis urna id. Ullamcorper ornare aliquet turpis nulla. Purus risus pellentesque purus quis elit ornat nunc. Pretium in non laorls posuere nec sagittis duis Est morbi laoreet eu lorem.',
        status: 'Ongoing',
        date: '2 wks ago',
      },
      {
        id: 2,
        title: 'Cooks Needed',
        description:
          'Lorem ipsum dolor sit amet, consectetur. Molestie at arma feugiat turpis urna id. Ullamcorper ornare aliquet turpis nulla. Purus risus pellentesque purus quis elit ornat nunc. Pretium in non laorls posuere nec sagittis duis Est morbi laoreet eu lorem.',
        status: 'Completed',
        date: '2 wks ago',
      },
      {
        id: 3,
        title: 'Cooks Needed',
        description:
          'Lorem ipsum dolor sit amet, consectetur. Molestie at arma feugiat turpis urna id. Ullamcorper ornare aliquet turpis nulla. Purus risus pellentesque purus quis elit ornat nunc. Pretium in non laorls posuere nec sagittis duis Est morbi laoreet eu lorem.',
        status: 'Completed',
        date: '2 wks ago',
      },
    ],
  },
  {
    id: 2,
    name: 'James Hadish',
    occupation: 'Marketing Coordinator',
    email: 'sara.cruz@example.com',
    balance: 'N25,000.00',
    dateRegistered: 'Feb 25, 2022',
    status: 'Verified',
    avatar: '/avatar-placeholder.png',
    phone: '+234 903 828 3447',
    state: 'Abuja',
    address: '2972 Westheimer Rd. Santa Ana, Illinois 85486',
    totalDeposited: 'NGN 200,000.00',
    totalSpent: 'NGN 100,000.00',
    currentBalance: 'NGN 100,000.00',
    jobsPosted: 2,
    hiredGiggz: 2,
    hoursPaid: 214,
    reviews: [],
    jobs: [],
  },
  {
    id: 3,
    name: 'James Hadish',
    occupation: 'Medical Assistant',
    email: 'michael.mitc@example.com',
    balance: 'N40,000.00',
    dateRegistered: 'Feb 25, 2022',
    status: 'Verified',
    avatar: '/avatar-placeholder.png',
    phone: '+234 903 828 3447',
    state: 'Abuja',
    address: '2972 Westheimer Rd. Santa Ana, Illinois 85486',
    totalDeposited: 'NGN 200,000.00',
    totalSpent: 'NGN 100,000.00',
    currentBalance: 'NGN 100,000.00',
    jobsPosted: 2,
    hiredGiggz: 2,
    hoursPaid: 214,
    reviews: [],
    jobs: [],
  },
  {
    id: 4,
    name: 'James Hadish',
    occupation: 'Dog Trainer',
    email: 'debra.holt@example.com',
    balance: 'N80,000.00',
    dateRegistered: 'Feb 25, 2022',
    status: 'Verified',
    avatar: '/avatar-placeholder.png',
    phone: '+234 903 828 3447',
    state: 'Abuja',
    address: '2972 Westheimer Rd. Santa Ana, Illinois 85486',
    totalDeposited: 'NGN 200,000.00',
    totalSpent: 'NGN 100,000.00',
    currentBalance: 'NGN 100,000.00',
    jobsPosted: 2,
    hiredGiggz: 2,
    hoursPaid: 214,
    reviews: [],
    jobs: [],
  },
  {
    id: 5,
    name: 'James Hadish',
    occupation: 'Nursing Assistant',
    email: 'michael.mitc@example.com',
    balance: 'N10,000.00',
    dateRegistered: 'Feb 25, 2022',
    status: 'Unverified',
    avatar: '/avatar-placeholder.png',
    phone: '+234 903 828 3447',
    state: 'Abuja',
    address: '2972 Westheimer Rd. Santa Ana, Illinois 85486',
    totalDeposited: 'NGN 200,000.00',
    totalSpent: 'NGN 100,000.00',
    currentBalance: 'NGN 100,000.00',
    jobsPosted: 2,
    hiredGiggz: 2,
    hoursPaid: 214,
    reviews: [],
    jobs: [],
  },
  {
    id: 6,
    name: 'James Hadish',
    occupation: 'President of Sales',
    email: 'tim.jennings@example.com',
    balance: 'N20,000.00',
    dateRegistered: 'Feb 25, 2022',
    status: 'Unverified',
    avatar: '/avatar-placeholder.png',
    phone: '+234 903 828 3447',
    state: 'Abuja',
    address: '2972 Westheimer Rd. Santa Ana, Illinois 85486',
    totalDeposited: 'NGN 200,000.00',
    totalSpent: 'NGN 100,000.00',
    currentBalance: 'NGN 100,000.00',
    jobsPosted: 2,
    hiredGiggz: 2,
    hoursPaid: 214,
    reviews: [],
    jobs: [],
  },
  {
    id: 7,
    name: 'James Hadish',
    occupation: 'Marketing Coordinator',
    email: 'curtis.weaver@example.com',
    balance: 'N20,000.00',
    dateRegistered: 'Feb 25, 2022',
    status: 'Blocked',
    avatar: '/avatar-placeholder.png',
    phone: '+234 903 828 3447',
    state: 'Abuja',
    address: '2972 Westheimer Rd. Santa Ana, Illinois 85486',
    totalDeposited: 'NGN 200,000.00',
    totalSpent: 'NGN 100,000.00',
    currentBalance: 'NGN 100,000.00',
    jobsPosted: 2,
    hiredGiggz: 2,
    hoursPaid: 214,
    reviews: [],
    jobs: [],
  },
]

export const userStats = {
  allUsers: 75531,
  verifiedUsers: 56123,
  unverifiedUsers: 9000,
  blockedUsers: 10405,
}
