export const mockServiceProviders = [
  {
    id: 1,
    name: 'Courtney Henry',
    occupation: 'Dispatch',
    email: 'sara.cruz@example.com',
    totalEarned: 'N20,000.00',
    dateRegistered: 'Feb 25, 2022',
    status: 'Verified',
    avatar: '/avatar-placeholder.png',
    phone: '+234 903 828 3447',
    state: 'Abuja',
    address: '2972 Westheimer Rd. Santa Ana, Illinois 85486',
    totalMoneyEarned: 'NGN 200,000.00',
    totalMoneyWithdrawn: 'NGN 100,000.00',
    currentBalance: 'NGN 100,000.00',
    completeGiggz: 23,
    appliedGiggz: 9,
    hoursWorked: 212,
    bio: 'I have 5 years experience in the plumbing industry with a passion for delivering exceptional service driving overall satisfaction.',
    reviews: [
      {
        id: 1,
        title: 'Responsive client',
        content:
          'A wonderful client to work with! He had a clear vision for the project and provided detailed specifications. Communication was excellent throughout the process, and he was always responsive and accommodating. It was a pleasure bringing his ideas to life. Highly recommended!',
        reviewer: 'Suleman Blakes',
        rating: 4,
        date: '2 wks ago',
      },
      {
        id: 2,
        title: 'Responsive client',
        content:
          'A wonderful client to work with! He had a clear vision for the project and provided detailed specifications. Communication was excellent throughout the process, and he was always responsive and accommodating. It was a pleasure bringing his ideas to life. Highly recommended!',
        reviewer: 'Jenny Wilson',
        rating: 4,
        date: '2 wks ago',
      },
      {
        id: 3,
        title: 'Responsive client',
        content:
          'A wonderful client to work with! He had a clear vision for the project and provided detailed specifications. Communication was excellent throughout the process, and he was always responsive and accommodating. It was a pleasure bringing his ideas to life. Highly recommended!',
        reviewer: 'Courtney Henry',
        rating: 4,
        date: '2 wks ago',
      },
    ],
    giggzHistory: [
      {
        id: 1,
        title: 'Plumber needed',
        client: 'Benedict Osita',
        description:
          'I need a good plumber that can help me fix a clogged zinc and broken pipe urgently. I need a good plumber that can help me fix a clogged zinc and broken pipe urgently!',
        location: 'Life Camp, FCT Abuja',
        status: 'Completed',
        date: '2 wks ago',
      },
      {
        id: 2,
        title: 'Plumber needed',
        client: 'Benedict Osita',
        description:
          'I need a good plumber that can help me fix a clogged zinc and broken pipe urgently. I need a good plumber that can help me fix a clogged zinc and broken pipe urgently!',
        location: 'Life Camp, FCT Abuja',
        status: 'Completed',
        date: '2 wks ago',
      },
      {
        id: 3,
        title: 'Plumber needed',
        client: 'Benedict Osita',
        description:
          'I need a good plumber that can help me fix a clogged zinc and broken pipe urgently. I need a good plumber that can help me fix a clogged zinc and broken pipe urgently!',
        location: 'Life Camp, FCT Abuja',
        status: 'Ongoing',
        date: '2 wks ago',
      },
    ],
  },
  {
    id: 2,
    name: 'Ralph Edwards',
    occupation: 'Teacher',
    email: 'sara.cruz@example.com',
    totalEarned: 'N25,000.00',
    dateRegistered: 'Feb 25, 2022',
    status: 'Verified',
    avatar: '/avatar-placeholder.png',
    phone: '+234 903 828 3447',
    state: 'Abuja',
    address: '2972 Westheimer Rd. Santa Ana, Illinois 85486',
    totalMoneyEarned: 'NGN 200,000.00',
    totalMoneyWithdrawn: 'NGN 100,000.00',
    currentBalance: 'NGN 100,000.00',
    completeGiggz: 15,
    appliedGiggz: 5,
    hoursWorked: 180,
    bio: 'Professional teacher with 8 years experience in education and tutoring.',
    reviews: [],
    giggzHistory: [],
  },
  {
    id: 3,
    name: 'Jenny Wilson',
    occupation: 'Cleaner',
    email: 'michael.mitc@example.com',
    totalEarned: 'N40,000.00',
    dateRegistered: 'Feb 25, 2022',
    status: 'Verified',
    avatar: '/avatar-placeholder.png',
    phone: '+234 903 828 3447',
    state: 'Abuja',
    address: '2972 Westheimer Rd. Santa Ana, Illinois 85486',
    totalMoneyEarned: 'NGN 200,000.00',
    totalMoneyWithdrawn: 'NGN 100,000.00',
    currentBalance: 'NGN 100,000.00',
    completeGiggz: 30,
    appliedGiggz: 12,
    hoursWorked: 250,
    bio: 'Experienced cleaner providing professional cleaning services.',
    reviews: [],
    giggzHistory: [],
  },
  {
    id: 4,
    name: 'Kathryn Murphy',
    occupation: 'Mechanic',
    email: 'debra.holt@example.com',
    totalEarned: 'N80,000.00',
    dateRegistered: 'Feb 25, 2022',
    status: 'Verified',
    avatar: '/avatar-placeholder.png',
    phone: '+234 903 828 3447',
    state: 'Abuja',
    address: '2972 Westheimer Rd. Santa Ana, Illinois 85486',
    totalMoneyEarned: 'NGN 200,000.00',
    totalMoneyWithdrawn: 'NGN 100,000.00',
    currentBalance: 'NGN 100,000.00',
    completeGiggz: 45,
    appliedGiggz: 18,
    hoursWorked: 320,
    bio: 'Skilled mechanic with expertise in automotive repair and maintenance.',
    reviews: [],
    giggzHistory: [],
  },
  {
    id: 5,
    name: 'Robert Fox',
    occupation: 'Teacher',
    email: 'michael.mitc@example.com',
    totalEarned: 'N10,000.00',
    dateRegistered: 'Feb 25, 2022',
    status: 'Unverified',
    avatar: '/avatar-placeholder.png',
    phone: '+234 903 828 3447',
    state: 'Abuja',
    address: '2972 Westheimer Rd. Santa Ana, Illinois 85486',
    totalMoneyEarned: 'NGN 50,000.00',
    totalMoneyWithdrawn: 'NGN 25,000.00',
    currentBalance: 'NGN 25,000.00',
    completeGiggz: 8,
    appliedGiggz: 3,
    hoursWorked: 60,
    bio: 'New teacher looking to provide quality tutoring services.',
    reviews: [],
    giggzHistory: [],
  },
  {
    id: 6,
    name: 'Dianne Russell',
    occupation: 'Dispatch',
    email: 'tim.jennings@example.com',
    totalEarned: 'N20,000.00',
    dateRegistered: 'Feb 25, 2022',
    status: 'Unverified',
    avatar: '/avatar-placeholder.png',
    phone: '+234 903 828 3447',
    state: 'Abuja',
    address: '2972 Westheimer Rd. Santa Ana, Illinois 85486',
    totalMoneyEarned: 'NGN 100,000.00',
    totalMoneyWithdrawn: 'NGN 50,000.00',
    currentBalance: 'NGN 50,000.00',
    completeGiggz: 12,
    appliedGiggz: 6,
    hoursWorked: 95,
    bio: 'Reliable dispatch service provider with good communication skills.',
    reviews: [],
    giggzHistory: [],
  },
  {
    id: 7,
    name: 'Brooklyn Simmons',
    occupation: 'Mechanic',
    email: 'curtis.weaver@example.com',
    totalEarned: 'N20,000.00',
    dateRegistered: 'Feb 25, 2022',
    status: 'Blocked',
    avatar: '/avatar-placeholder.png',
    phone: '+234 903 828 3447',
    state: 'Abuja',
    address: '2972 Westheimer Rd. Santa Ana, Illinois 85486',
    totalMoneyEarned: 'NGN 80,000.00',
    totalMoneyWithdrawn: 'NGN 40,000.00',
    currentBalance: 'NGN 40,000.00',
    completeGiggz: 20,
    appliedGiggz: 8,
    hoursWorked: 150,
    bio: 'Experienced mechanic specializing in engine repairs.',
    reviews: [],
    giggzHistory: [],
  },
]
